package gams:scaler@1.0.0;

interface scaler {
    type data-entry = tuple<string, string>;

    record tile-layer {
        width: u32,
        data: list<u32>,
        props: list<data-entry>,
    }

    record tile-map {
        layers: list<tile-layer>,
        props: list<data-entry>,
    }

    record door-size {
        width: u32,
        height: u32,
    }

    record door-sizes-config {
        north: door-size,
        east: door-size,
        south: door-size,
        west: door-size,
    }

    record scale-config {
        scale-factor: u32,
        door-sizes: option<door-sizes-config>,
    }

    scale: func(src: tile-map, config: scale-config) -> result<tile-map, string>;
}

world scaler-plugin {
    include wasi:cli/imports@0.2.0;

    export scaler;
}
